/* A lexical scanner generated by flex*/

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* Some routines like yy_flex_realloc() are emitted as static but are
   not called by all lexers. This generates warnings in some compilers,
   notably GCC. Arrange to suppress these. */
#ifdef __GNUC__
#define YY_MAY_BE_UNUSED __attribute__((unused))
#else
#define YY_MAY_BE_UNUSED
#endif

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t )) YY_MAY_BE_UNUSED;
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define FLEX_DEBUG
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;

#define FLEX_DEBUG
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 48
#define YY_END_OF_BUFFER 49
static yyconst short int yy_accept[180] =
    {   0,
        0,    0,    0,    0,   49,   47,    3,    2,    1,    9,
       45,    9,   47,    9,    4,    4,    9,    9,    9,   46,
       46,   46,   46,    9,   48,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,    9,   47,   41,
       43,    1,   42,    1,   13,   45,   44,   45,   14,    8,
       17,    6,    4,    0,   10,   12,   11,   46,   46,   46,
       46,   46,   16,   46,   46,   46,   46,   46,   46,   46,
       46,   31,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   15,   41,    1,   40,   45,   44,   45,   17,
        6,    0,    5,   46,   46,   46,   46,   46,   46,   46,

       46,   46,   46,   29,   46,   19,   35,   46,   46,   46,
       46,   46,   46,   46,   45,   45,    0,    6,   46,   46,
       46,   21,   46,   46,   46,   32,   46,   46,   46,   46,
       25,   46,   46,   26,    7,   18,   46,   45,   45,   46,
       37,   46,   46,   34,   23,   46,   46,   46,   46,   46,
       46,   30,   46,   46,   46,   20,   46,   46,   46,   33,
       22,   46,   46,   46,   27,   46,   46,   36,   46,   39,
       46,   46,   46,   46,   24,   46,   28,   38,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    1,    7,
        7,    9,   10,    7,   11,   12,   13,   14,   15,   15,
       15,   15,   15,   15,   15,   15,   15,    1,    7,   16,
       17,   18,    1,    1,   19,   20,   20,   20,   21,   20,
       22,   22,   23,   22,   22,   24,   22,   25,   22,   26,
       22,   27,   22,   22,   22,   22,   22,   28,   22,   22,
       29,   30,   31,    1,   32,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   42,   49,   50,   51,   52,   53,   54,   55,
       56,   42,   57,   58,   57,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    4,    1,
        1,    1,    1,    5,    5,    1,    1,    1,    5,    5,
        5,    6,    6,    6,    6,    6,    6,    6,    1,    1,
        1,    6,    5,    5,    5,    5,    5,    5,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    1,    1
    } ;

static yyconst short int yy_base[190] =
    {   0,
        0,    0,   56,   58,  201,  753,  753,  753,  196,  172,
       57,  753,  178,   55,   57,   61,  136,  129,  124,   63,
       65,   67,   69,  109,  753,   75,   77,   79,   99,  103,
      113,  105,  115,  124,  134,  146,  148,  753,   67,    0,
      753,  119,  102,  101,  753,   68,  753,   80,  753,  753,
        0,  150,  155,    0,  753,  753,  753,    0,  158,  162,
      167,  170,  753,  177,  181,  190,  183,  196,  205,  211,
      215,  217,  219,  225,  227,  230,  238,  246,  251,  254,
      258,  270,  753,    0,   96,  753,  102,   66,  138,    0,
      273,  286,    0,  289,  298,  300,  302,  305,  308,  311,

      327,  333,  335,  337,  339,  341,  347,  360,  362,  366,
      373,  376,  385,  387,   58,  149,   89,  119,  395,  397,
      401,  420,  422,  424,  426,  428,  431,  435,  447,  454,
      461,  466,  468,  473,  475,  477,  480,   40,  206,  487,
      496,  506,  508,  510,  512,  516,  518,  531,  541,  543,
      545,  550,  553,  555,  566,  576,  578,  581,  587,  585,
      589,  600,  608,  610,  612,  616,  619,  621,  635,  623,
      643,  645,  649,  651,  655,  657,  664,  670,  753,  706,
      712,  714,  720,  726,  732,   61,  734,  740,  746
    } ;

static yyconst short int yy_def[190] =
    {   0,
      179,    1,  180,  180,  179,  179,  179,  179,  179,  179,
      181,  179,  179,  179,  179,  179,  179,  179,  179,  182,
      182,  182,  182,  179,  179,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  179,  179,  183,
      179,  183,  179,  179,  179,  181,  179,  184,  179,  179,
      185,  179,  179,  186,  179,  179,  179,  187,  182,  182,
      182,  182,  179,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  179,  183,  183,  179,  181,  188,  184,  185,
      179,  179,  186,  182,  182,  182,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  188,  189,  179,  179,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  188,  189,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  182,  182,    0,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179
    } ;

static yyconst short int yy_nxt[812] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   12,   12,
       12,   12,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   21,   22,   23,   20,   24,    6,
       12,   25,   20,   26,   27,   28,   29,   30,   20,   20,
       31,   20,   20,   20,   20,   32,   20,   20,   33,   34,
       35,   20,   36,   37,   20,   20,   38,   39,   41,   42,
       41,   42,   47,   50,   43,   93,   43,   51,   52,  116,
       53,   53,   52,   47,   53,   53,   58,   58,   58,   58,
       58,   58,   58,   58,   54,   88,   48,  116,   58,   58,
       58,   58,   58,   58,   58,  116,   58,   48,   58,   85,

       58,   60,  118,  118,   44,   62,   58,   47,   58,   89,
       58,   54,   58,   58,   86,   61,   58,   58,   58,   58,
       66,   64,   85,   65,   83,   67,   58,   58,   58,   58,
       58,   48,  118,  118,   58,   70,   58,   58,   58,   63,
       57,   75,   68,   88,   58,   56,   58,   58,   58,   71,
       72,   77,   55,   69,  115,   58,   76,   73,   74,   58,
       58,   58,   58,   91,   91,   58,   52,   89,   53,   53,
       92,   58,   58,   79,   78,   58,   58,   58,  139,   58,
       58,   58,   80,   58,   58,   49,   92,   82,   45,   58,
       58,   58,   81,   58,   58,   58,   58,   58,   58,   44,

      179,   58,   96,   58,   58,  179,  179,   95,   58,   58,
       58,  115,   58,  179,   58,   94,  179,   98,   58,   58,
      179,   58,   99,   97,   58,   58,  179,   58,   58,   58,
       58,   58,   58,   58,  100,  139,   58,  179,   58,   58,
       58,   58,   58,   58,   58,  101,   58,  179,   58,  179,
       58,   58,   58,  179,  103,  102,   58,  179,   58,   58,
       58,   58,  179,  104,   58,   58,  105,   58,   58,   58,
      179,   58,   58,  108,  179,  106,  179,   58,  179,  179,
      107,  179,   58,   58,   58,   58,   91,   91,  109,   58,
      179,  111,  179,   92,  110,  117,  117,  179,  113,  118,

      118,   58,   58,   58,  179,  112,  179,  119,  179,   92,
      114,   58,   58,   58,   58,   58,   58,  179,   58,   58,
       58,   58,   58,  179,   58,   58,  179,  179,  179,   58,
      179,   58,  179,   58,  179,  121,   58,  123,  179,   58,
       58,   58,   58,  120,  125,  122,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   58,  179,  124,   58,  179,
       58,   58,  179,  126,   58,  179,   58,  179,   58,  127,
       58,  179,   58,   58,   58,   58,   58,  130,   58,   58,
       58,  179,  129,  179,  128,  179,   58,   58,  179,   58,
       58,   58,  179,   58,  179,  179,  179,   58,   58,   58,

       58,   58,  179,  131,   58,  179,  133,   58,   58,   58,
       58,   58,  135,  132,   58,   58,   58,  179,   58,  179,
      136,  179,  134,  142,  143,  179,   58,  179,   58,  179,
      137,  179,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,  140,   58,   58,  179,  141,   58,   58,
      179,   58,  179,   58,  179,   58,  179,   58,  179,   58,
       58,   58,   58,  179,  144,  179,   58,   58,   58,  146,
      179,  135,  179,  145,   58,   58,  147,  179,   58,   58,
       58,   58,   58,  148,  179,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,  179,  179,   58,  179,   58,

       58,   58,  149,  179,   58,  179,   58,  179,   58,   58,
       58,   58,  179,  151,  150,  179,  152,  179,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,  179,   58,
       58,   58,   58,  179,  179,  153,  179,   58,  179,   58,
      179,   58,  179,   58,   58,   58,  179,   58,  155,   58,
      179,  154,  156,  157,   58,   58,   58,   58,   58,   58,
      179,  179,   58,   58,   58,  179,   58,   58,   58,   58,
      179,  179,   58,  179,   58,  158,   58,  179,  159,   58,
       58,   58,  179,  161,   58,  162,   58,  179,  160,   58,
       58,   58,   58,  179,   58,   58,  179,   58,   58,   58,

       58,   58,   58,   58,  179,  163,  179,   58,  179,   58,
      179,  164,   58,   58,   58,  179,   58,  166,   58,  167,
       58,   58,   58,   58,   58,   58,   58,  165,  179,   58,
       58,   58,   58,   58,   58,   58,   58,   58,  179,   58,
      179,   58,  179,   58,  169,  179,  170,   58,   58,   58,
       58,  179,   58,  172,   58,  168,   58,   58,   58,   58,
      179,  171,   58,   58,   58,   58,   58,  179,   58,   58,
       58,   58,  179,  173,   58,  179,   58,   58,   58,  179,
       58,  175,   58,   58,   58,  176,   58,  179,   58,  179,
      179,  179,  179,  174,  179,   58,  179,  179,  179,  179,

      177,   58,  179,  179,  179,  178,   40,   40,   40,   40,
       40,   40,   46,  179,   46,   46,   46,   46,   59,   59,
       84,  179,   84,  179,   84,   84,   87,  179,   87,   87,
       87,   87,   90,  179,   90,   90,   90,   90,   58,   58,
      115,  179,  179,  115,  115,  115,  138,  179,  138,  138,
      138,  138,    5,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,

      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179
    } ;

static yyconst short int yy_chk[812] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        4,    4,   11,   14,    3,  186,    4,   14,   15,  138,
       15,   15,   16,   46,   16,   16,   20,   20,   21,   21,
       22,   22,   23,   23,   15,   48,   11,  115,   26,   26,
       27,   27,   28,   28,   20,   88,   21,   46,   22,   85,

       23,   21,  117,  117,   44,   23,   26,   87,   27,   48,
       28,   15,   29,   29,   43,   22,   30,   30,   32,   32,
       27,   26,   42,   26,   39,   28,   31,   31,   33,   33,
       29,   87,  118,  118,   30,   30,   32,   34,   34,   24,
       19,   32,   29,   89,   31,   18,   33,   35,   35,   30,
       31,   33,   17,   29,  116,   34,   32,   31,   31,   36,
       36,   37,   37,   52,   52,   35,   53,   89,   53,   53,
       52,   59,   59,   35,   34,   60,   60,   36,  116,   37,
       61,   61,   35,   62,   62,   13,   52,   37,   10,   59,
       64,   64,   36,   60,   65,   65,   67,   67,   61,    9,

        5,   62,   62,   66,   66,    0,    0,   61,   64,   68,
       68,  139,   65,    0,   67,   60,    0,   65,   69,   69,
        0,   66,   66,   64,   70,   70,    0,   68,   71,   71,
       72,   72,   73,   73,   67,  139,   69,    0,   74,   74,
       75,   75,   70,   76,   76,   68,   71,    0,   72,    0,
       73,   77,   77,    0,   70,   69,   74,    0,   75,   78,
       78,   76,    0,   71,   79,   79,   73,   80,   80,   77,
        0,   81,   81,   76,    0,   74,    0,   78,    0,    0,
       75,    0,   79,   82,   82,   80,   91,   91,   77,   81,
        0,   79,    0,   91,   78,   92,   92,    0,   81,   92,

       92,   82,   94,   94,    0,   80,    0,   94,    0,   91,
       82,   95,   95,   96,   96,   97,   97,    0,   98,   98,
       94,   99,   99,    0,  100,  100,    0,    0,    0,   95,
        0,   96,    0,   97,    0,   96,   98,   98,    0,   99,
      101,  101,  100,   95,  100,   97,  102,  102,  103,  103,
      104,  104,  105,  105,  106,  106,    0,   99,  101,    0,
      107,  107,    0,  101,  102,    0,  103,    0,  104,  102,
      105,    0,  106,  108,  108,  109,  109,  106,  107,  110,
      110,    0,  105,    0,  103,    0,  111,  111,    0,  112,
      112,  108,    0,  109,    0,    0,    0,  110,  113,  113,

      114,  114,    0,  108,  111,    0,  110,  112,  119,  119,
      120,  120,  112,  109,  121,  121,  113,    0,  114,    0,
      113,    0,  111,  121,  121,    0,  119,    0,  120,    0,
      114,    0,  121,  122,  122,  123,  123,  124,  124,  125,
      125,  126,  126,  119,  127,  127,    0,  120,  128,  128,
        0,  122,    0,  123,    0,  124,    0,  125,    0,  126,
      129,  129,  127,    0,  123,    0,  128,  130,  130,  125,
        0,  128,    0,  124,  131,  131,  127,    0,  129,  132,
      132,  133,  133,  129,    0,  130,  134,  134,  135,  135,
      136,  136,  131,  137,  137,    0,    0,  132,    0,  133,

      140,  140,  130,    0,  134,    0,  135,    0,  136,  141,
      141,  137,    0,  133,  132,    0,  137,    0,  140,  142,
      142,  143,  143,  144,  144,  145,  145,  141,    0,  146,
      146,  147,  147,    0,    0,  140,    0,  142,    0,  143,
        0,  144,    0,  145,  148,  148,    0,  146,  143,  147,
        0,  142,  146,  147,  149,  149,  150,  150,  151,  151,
        0,    0,  148,  152,  152,    0,  153,  153,  154,  154,
        0,    0,  149,    0,  150,  148,  151,    0,  149,  155,
      155,  152,    0,  151,  153,  153,  154,    0,  150,  156,
      156,  157,  157,    0,  158,  158,    0,  155,  160,  160,

      159,  159,  161,  161,    0,  154,    0,  156,    0,  157,
        0,  155,  158,  162,  162,    0,  160,  158,  159,  159,
      161,  163,  163,  164,  164,  165,  165,  157,    0,  166,
      166,  162,  167,  167,  168,  168,  170,  170,    0,  163,
        0,  164,    0,  165,  163,    0,  164,  166,  169,  169,
      167,    0,  168,  167,  170,  162,  171,  171,  172,  172,
        0,  166,  173,  173,  174,  174,  169,    0,  175,  175,
      176,  176,    0,  169,  171,    0,  172,  177,  177,    0,
      173,  172,  174,  178,  178,  173,  175,    0,  176,    0,
        0,    0,    0,  171,    0,  177,    0,    0,    0,    0,

      174,  178,    0,    0,    0,  176,  180,  180,  180,  180,
      180,  180,  181,    0,  181,  181,  181,  181,  182,  182,
      183,    0,  183,    0,  183,  183,  184,    0,  184,  184,
      184,  184,  185,    0,  185,  185,  185,  185,  187,  187,
      188,    0,    0,  188,  188,  188,  189,    0,  189,  189,
      189,  189,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,

      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 1;

static yyconst short int yy_rule_linenum[48] =
    {   0,
       85,   89,   94,   98,  105,  111,  116,  124,  128,  132,
      136,  140,  145,  149,  153,  157,  161,  165,  169,  173,
      177,  181,  185,  189,  193,  197,  201,  205,  209,  213,
      217,  221,  225,  229,  233,  237,  241,  245,  249,  255,
      256,  257,  258,  265,  272,  276,  284
    } ;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#define INITIAL 0
/* File:  scanner.l
 * ----------------
 * Lex input file to generate the scanner for the compiler.
 */
#line 7 "scanner.l"

/* The text within this first region delimited by %{ and %} is assumed to
 * be C/C++ code and will be copied verbatim to the lex.yy.c file ahead
 * of the definitions of the yylex() function. Add other header file inclusions
 * or C++ variable declarations/prototypes that are needed by your code here.
 */

#include <string.h>
#include "scanner.h"
#include "utility.h" // for PrintDebug()
#include "errors.h"
#include <stdio.h>
#include <iostream>

int currLine = 0; 
int currCol = 0; 

/* Global variable: yylval
 * -----------------------
 * This global variable is how we get attribute information about the token
 * just scanned to the client. The scanner sets the global variable
 * appropriately and since it's global the client can just read it.  In the
 * future, this variable will be declared for us in the y.tab.c file
 * produced by Yacc, but for now, we declare it manually.
 */
YYSTYPE yylval;  // manually declared for pp1, later Yacc provides

/* Global variable: yylloc
 * -----------------------
 * This global variable is how we get position information about the token
 * just scanned to the client. (Operates similarly to yylval above)
 */
struct yyltype yylloc; // manually dclared for pp1, later Yacc provides

/* Macro: YY_USER_ACTION 
 * ---------------------
 * This flex built-in macro can be defined to provide an action which is
 * always executed prior to any matched rule's action. Basically, it is
 * a way of having a piece of code common to all actions factored out to
 * this routine.  We already defined it for you and left the empty
 * function DoBeforeEachAction ready for your use as needed. It will
 * be called once for each pattern scanned from the file, before
 * executing its action.
 */
static void DoBeforeEachAction(); 
#define YY_USER_ACTION DoBeforeEachAction();

/* The section before the first %% is the Definitions section of the lex
* input file. Here is where you set options for the scanner, define lex
* states, and can set up definitions to give names to regular expressions
* as a simple substitution mechanism that allows for more readable
* entries in the Rules section later. 
*/
#define IN_COMMENT 1

#line 687 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 80 "scanner.l"

 /* All patterns and actions should be placed between the start and stop
  * %% markers which delimit the Rules section. 
  */ 
  
#line 844 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 180 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 753 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */

		if ( yy_flex_debug )
			{
			if ( yy_act == 0 )
				fprintf( stderr, "--scanner backing up\n" );
			else if ( yy_act < 48 )
				fprintf( stderr, "--accepting rule at line %d (\"%s\")\n",
				         yy_rule_linenum[yy_act], yytext );
			else if ( yy_act == 48 )
				fprintf( stderr, "--accepting default rule (\"%s\")\n",
				         yytext );
			else if ( yy_act == 49 )
				fprintf( stderr, "--(end of buffer or a NUL)\n" );
			else
				fprintf( stderr, "--EOF (start condition %d)\n", YY_START );
			}

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 85 "scanner.l"
{
	
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 89 "scanner.l"
{ 
	currLine++; 
	currCol = 1; 
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 94 "scanner.l"
{
	currCol += 8;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 98 "scanner.l"
{ 

	yylval.integerConstant = atoi(yytext); 
	
	return T_IntConstant; 
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 105 "scanner.l"
{
	yylval.integerConstant = (int)strtod(yytext, NULL); 
	return T_IntConstant; 
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 111 "scanner.l"
{
	yylval.doubleConstant = strtod(yytext, NULL) ;
	return T_DoubleConstant; 
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 116 "scanner.l"
{
	if (yytext[0] == 't')
		yylval.boolConstant = true; 
	else if (yytext[0] == 'f')
		yylval.boolConstant = false; 
	return T_BoolConstant; 
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 124 "scanner.l"
{
	BEGIN(IN_COMMENT); 
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 128 "scanner.l"
{
	return yytext[0]; 
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 132 "scanner.l"
{
	return T_LessEqual; 
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 136 "scanner.l"
{
	return T_GreaterEqual; 
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 140 "scanner.l"
{

	return T_Equal; 
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 145 "scanner.l"
{
	return T_NotEqual; 
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 149 "scanner.l"
{
	return T_And; 
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 153 "scanner.l"
{
	return T_Or; 
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 157 "scanner.l"
{
	return T_Dims; 
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 161 "scanner.l"
{
	//ignores one line comments
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 165 "scanner.l"
{
	return T_Void; 
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 169 "scanner.l"
{
	return T_Int; 
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 173 "scanner.l"
{
	return T_Double; 
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 177 "scanner.l"
{
	return T_Bool; 
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 181 "scanner.l"
{
	return T_String; 
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 185 "scanner.l"
{
	return T_Class; 
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 189 "scanner.l"
{
	return T_Interface; 
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 193 "scanner.l"
{
	return T_Null; 
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 197 "scanner.l"
{
	return T_This; 
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 201 "scanner.l"
{
	return T_Extends; 
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 205 "scanner.l"
{
	return T_Implements; 
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 209 "scanner.l"
{
	return T_For; 
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 213 "scanner.l"
{
	return T_While; 
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 217 "scanner.l"
{
	return T_If; 
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 221 "scanner.l"
{
	return T_Else; 
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 225 "scanner.l"
{
	return T_Return; 
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 229 "scanner.l"
{
	return T_Break; 
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 233 "scanner.l"
{
	return T_New; 
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 237 "scanner.l"
{
	return T_NewArray; 
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 241 "scanner.l"
{
	return T_Print; 
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 245 "scanner.l"
{
	return T_ReadInteger; 
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 249 "scanner.l"
{
	return T_ReadLine; 
}
	YY_BREAK

case 40:
YY_RULE_SETUP
#line 255 "scanner.l"
{ BEGIN(INITIAL); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 256 "scanner.l"
// eat comment in chunks
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 257 "scanner.l"
// eat the lone star
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 258 "scanner.l"
{ currLine++; }
	YY_BREAK
case YY_STATE_EOF(IN_COMMENT):
#line 259 "scanner.l"
{
     	ReportError::UntermComment(); 
     	yyterminate(); 
     	}
	YY_BREAK

case 44:
YY_RULE_SETUP
#line 265 "scanner.l"
{
	//s = s.substr(1, yyleng-2); 
	yylval.stringConstant = yytext; 
	return T_StringConstant; 
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 272 "scanner.l"
{
	ReportError::UntermString(&yylloc, yytext); 
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 276 "scanner.l"
{
	if (yyleng > 31)
		ReportError::LongIdentifier(&yylloc, yytext); 
//	int a = sscanf(yytext, "%31s", yylval.identifier);  
	strncpy(yylval.identifier, yytext, 31); 
	return T_Identifier; 
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 284 "scanner.l"
{
	ReportError::UnrecogChar(&yylloc, yytext[0]); 
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 288 "scanner.l"
ECHO;
	YY_BREAK
#line 1294 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 180 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 180 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 179);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 288 "scanner.l"

/* The closing %% above marks the end of the Rules section and the beginning
 * of the User Subroutines section. All text from here to the end of the
 * file is copied verbatim to the end of the generated lex.yy.c file.
 * This section is where you put definitions of helper functions.
 */


/* Function: InitScanner
 * ---------------------
 * This function will be called before any calls to yylex().  It is designed
 * to give you an opportunity to do anything that must be done to initialize
 * the scanner (set global variables, configure starting state, etc.). One
 * thing it already does for you is assign the value of the global variable
 * yy_flex_debug that controls whether flex prints debugging information
 * about each token and what rule was matched. If set to false, no information
 * is printed. Setting it to true will give you a running trail that might
 * be helpful when debugging your scanner. Please be sure the variable is
 * set to false when submitting your final version.
 */
void InitScanner()
{
    PrintDebug("lex", "Initializing scanner");
    yy_flex_debug = false;
    currLine = 1; 
    currCol = 1; 
}


/* Function: DoBeforeEachAction()
 * ------------------------------
 * This function is installed as the YY_USER_ACTION. This is a place
 * to group code common to all actions.
 */
static void DoBeforeEachAction()
{
 
	yylloc.first_line = currLine; 
	yylloc.last_line = currLine; 
	yylloc.first_column = currCol; 
	
	currCol += yyleng;  
	

	yylloc.last_column = currCol - 1; 

	
}
